{
  "openapi": "3.0.0",
  "info": {
    "title": "API Documentations",
    "description": "List api Haitoko Test",
    "version": "1.0.0",
    "contact": {
      "name": "Dio Yoga Pratama",
      "email": "dyopratama6@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3030",
      "description": "local"
    }
  ],

  "tags": [
    {
      "name": "Auth",
      "description": "Authentication"
    },
    {
      "name": "Users",
      "description": "API For Users"
    },
    {
      "name": "Category",
      "description": "API for Category"
    },
    {
      "name": "Product",
      "description": "API for Product"
    }
  ],

  "paths": {
    "/auth/register": {
      "post": {
        "summary": "Register Authentication",
        "tags": ["Auth"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  },
                  "phone_number": {
                    "type": "string"
                  },
                  "gender": {
                    "type": "string"
                  },
                  "role": {
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "email",
                  "password",
                  "phone_number",
                  "gender",
                  "role"
                ]
              },
              "examples": {
                "value": {
                  "name": "yourname",
                  "email": "demo@mail.com",
                  "password": "yourpasword",
                  "gender": "L/P",
                  "phone_number": 0,
                  "role": "Administrator/Buyer"
                }
              }
            }
          },
          "description": ""
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "operationId": "Registration"
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Login",
        "operationId": "login",
        "description": "Login Authentication",
        "tags": ["Auth"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": ["email", "password"]
              },
              "examples": {
                "value": {
                  "email": "demo@rocketmail.net",
                  "password": "yourpassword"
                }
              }
            }
          },
          "description": ""
        },
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request (Invalid request body)"
          },
          "404": {
            "description": "Not Found (User not found or OAuth not valid)"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/auth/logout": {
      "get": {
        "summary": "Logout",
        "operationId": "logout",
        "description": "Logout",
        "tags": ["Auth"],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request (Invalid request body)"
          },
          "404": {
            "description": "Not Found (User not found or OAuth not valid)"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/auth/refreshToken": {
      "get": {
        "summary": "refreshToken",
        "operationId": "refreshToken",
        "description": "refreshToken",
        "tags": ["Auth"],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request (Invalid request body)"
          },
          "404": {
            "description": "Not Found (User not found or OAuth not valid)"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/middleware/users": {
      "get": {
        "summary": "Get all Users",
        "tags": ["Users"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br> 2. Buyer  ",
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "GetAllUsers"
      }
    },
    "/middleware/Users/{id}": {
      "get": {
        "summary": "Get One Users",
        "tags": ["Users"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br> 2. Buyer  ",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "GetOneUsers"
      },
      "put": {
        "summary": "Update Users",
        "tags": ["Users"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "gender": {
                    "type": "string"
                  },
                  "phone_number": {
                    "type": "string"
                  }
                },
                "required": ["name", "email", "gender", "phone_number"]
              },
              "examples": {
                "value": {
                  "name": "yourname",
                  "email": "yourname@example.com",

                  "gender": "L",

                  "phone_number": 0
                }
              }
            }
          },
          "description": ""
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br> 2. Buyer  ",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "UpdateUsers"
      },
      "delete": {
        "summary": "Delete Users",
        "tags": ["Users"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br>  ",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "DeleteUsers"
      }
    },
    "/middleware/Users/changepass": {
      "post": {
        "summary": "Change Password",
        "operationId": "Change Password",
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br> 2. Buyer  ",
        "tags": ["Users"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "oldPassword": {
                    "type": "string"
                  },
                  "newPassword": {
                    "type": "string"
                  },
                  "confirmPassword": {
                    "type": "string"
                  }
                },
                "required": ["oldPassword", "newPassword", "confirmPassword"]
              },
              "examples": {
                "value": {
                  "oldPassword": "yourpassword",
                  "newPassword": "yourpassword",
                  "confirmPassword": "yourpassword"
                }
              }
            }
          },
          "description": ""
        },
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request (Invalid request body)"
          },
          "404": {
            "description": "Not Found (User not found or OAuth not valid)"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "Authorization": []
          }
        ]
      }
    },
    "/category": {
      "get": {
        "summary": "Get All Category",
        "operationId": "category",
        "description": "Get All Category",
        "tags": ["Category"],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request (Invalid request body)"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/category/{id}": {
      "get": {
        "summary": "Get One Category",
        "tags": ["Category"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Get One Category",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "operationId": "GetOneCategory"
      }
    },
    "/middleware/category": {
      "post": {
        "summary": "Insert Category",
        "tags": ["Category"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "category_name": {
                    "type": "string"
                  }
                },
                "required": ["category_name"]
              },
              "examples": {
                "value": {
                  "category_name": "yourcategoryname"
                }
              }
            }
          },
          "description": ""
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br>",
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "InsertCategory"
      }
    },
    "/middleware/category/{id}": {
      "put": {
        "summary": "Update Category",
        "tags": ["Category"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "category_name": {
                    "type": "string"
                  }
                },
                "required": ["category_name"]
              },
              "examples": {
                "value": {
                  "category_name": "yourcategoryname"
                }
              }
            }
          },
          "description": ""
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br> ",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "UpdateCategory"
      },
      "delete": {
        "summary": "Delete Category",
        "tags": ["Category"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br>",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "DeleteCategory"
      }
    },
    "/product": {
      "get": {
        "summary": "Get All Product",
        "operationId": "product",
        "description": "Get All Product",
        "tags": ["Product"],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "application/json"
            },
            "in": "header",
            "name": "Accept",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request (Invalid request body)"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/product/{id}": {
      "get": {
        "summary": "Get One Product",
        "tags": ["Product"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "Get One Product",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "operationId": "GetOneProduct"
      }
    },
    "/middleware/product": {
      "post": {
        "summary": "Insert Product",
        "tags": ["Product"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "product_name": {
                    "type": "string"
                  },
                  "category_id": {
                    "type": "string",
                    "format": "uuid"
                  },
                  "stock": {
                    "type": "number"
                  },
                  "price": {
                    "type": "number",
                    "format": "double"
                  },
                  "discount": {
                    "type": "number",
                    "format": "double"
                  }
                },
                "required": [
                  "product_name",
                  "category_id",
                  "stock",
                  "price",
                  "discount"
                ]
              },
              "examples": {
                "value": {
                  "product_name": "yourproductname",
                  "category_id": "963a7091-b1c0-4d07-ea2a-77185b1da1de",
                  "stock": 0,
                  "price": 0,
                  "discount": 0
                }
              }
            }
          },
          "description": ""
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br>",
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "InsertCategory"
      }
    },
    "/middleware/product/{id}": {
      "put": {
        "summary": "Update Product",
        "tags": ["Product"],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "product_name": {
                    "type": "string"
                  },
                  "category_id": {
                    "type": "string",
                    "format": "uuid"
                  },
                  "stock": {
                    "type": "number"
                  },
                  "price": {
                    "type": "number",
                    "format": "double"
                  },
                  "discount": {
                    "type": "number",
                    "format": "double"
                  }
                },
                "required": [
                  "product_name",
                  "category_id",
                  "stock",
                  "price",
                  "discount"
                ]
              },
              "examples": {
                "value": {
                  "category_name": "yourcategoryname"
                }
              }
            }
          },
          "description": ""
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br> ",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "UpdateProduct"
      },
      "delete": {
        "summary": "Delete Product",
        "tags": ["Product"],
        "responses": {
          "200": {
            "description": "OK"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "description": "<strong>[Role Access]</strong> <br>1. Administrator <br>",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "in": "path",
            "name": "id",
            "required": true
          }
        ],
        "security": [
          {
            "Authorization": []
          }
        ],
        "operationId": "DeleteProduct"
      }
    }
  },

  "components": {
    "securitySchemes": {
      "Authorization": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
